# Generated by Django 6.0.3 on 2026-04-02 18:58

import django.db.models.deletion
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Где выполнять привычку?', max_length=255, verbose_name='Место')),
                ('time', models.TimeField(help_text='Во сколько выполнять привычку?', verbose_name='Время')),
                ('action', models.CharField(help_text='Что нужно сделать?', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Отметьте, если это приятная привычка (награда)', verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Как часто выполнять привычку (от 1 до 7 дней)', validators=[habits.validators.validate_periodicity], verbose_name='Периодичность (дни)')),
                ('reward', models.CharField(blank=True, help_text='Чем себя вознаградить после выполнения', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveSmallIntegerField(help_text='Сколько времени займет выполнение (не более 120 секунд)', validators=[habits.validators.validate_duration], verbose_name='Время на выполнение (сек)')),
                ('is_public', models.BooleanField(default=False, help_text='Отметьте, если привычка доступна всем', verbose_name='Публичная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Привычка, которая будет наградой (только для полезных привычек)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
    ]
